### ISSUE TITLE
PHP highlighting messed up in Atom Beta (1.21.0)

### ISSUE THREAD

**Issue by martinbean** [atom/one-dark-syntax#100]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The syntax highlighting of PHP files seems to be messed up in Atom Beta (version 1.21.0), compared to previous, stable versions of Atom.

### Steps to Reproduce

1. Open a PHP file in Atom (stable). Syntax highlighting is expected.
2. Open the same file in Atom Beta. Syntax highlighting is different.

**Expected behavior:** Same syntax highlighting as the stable version of Atom.

**Actual behavior:** Difference in syntax highlighting when compared to stable version of Atom.

**Reproduces how often:** Every time.

### Versions

1.21.0

### Additional Information

Screen-shot of PHP file in stable version of Atom:

![screen shot 2017-09-12 at 21 59 20](https://user-images.githubusercontent.com/167312/30348147-532c1016-9806-11e7-9b9d-00542ab4278b.png)

Screen-shot of same PHP file in Atom Beta:

![screen shot 2017-09-12 at 22 00 06](https://user-images.githubusercontent.com/167312/30348156-5cf008aa-9806-11e7-9390-2271e9f7bf46.png)

Differences:

* `Request` in imported namespace is yellow, instead of grey like the rest of the FQCN.
* Opening brace for class is yellow.
* `Response` in DocBlock parameter type-hint is yellow, instead of grey like the rest of the type-hint.
* The closing brace of methods is yellow, instead of grey like the opening brace.
* The call to the global `view()` function is blue, whereas it’s grey in the stable version of Atom.

I’ve only tried this file, so I don’t know if there are any more syntax highlighting inconsistencies between the stable and beta versions of Atom.

**Comment by martinbean** [comment]
Seems the trait syntax messes up further syntax highlighting too:

![screen shot 2017-09-12 at 22 20 03](https://user-images.githubusercontent.com/167312/30348824-a1cbdfba-9808-11e7-97bd-8909aaf964be.png)

**Comment by 50Wliu** [comment]
I believe both issues have already been fixed, and I will be looking into creating a patch release.

**Comment by martinbean** [comment]
@50Wliu Awesome! Thanks for addressing this Issue so quickly.

Is there an ETA on the patch version?

**Comment by martinbean** [comment]
These styling issues have made their way in the stable version of Atom for me now 😢

**Comment by 50Wliu** [comment]
I can't commit to a timeframe, but I can confirm that a hotfix will be released for these issues.

**Comment by mkarnicki** [comment]
Looking forward to it, @50Wliu . I can confirm 1.20.0 is also affected.
<img width="192" alt="screen shot 2017-09-14 at 20 14 49" src="https://user-images.githubusercontent.com/2966794/30446708-3daaddbe-998a-11e7-9070-277a070d628f.png">

**Comment by stefblokdijk** [comment]
Hey, i'm still having this issue. 
Didn't found any update yet that fixed this.

I made a little css fix to go back what I was used to.
Just add the css code to the atom styling.

### CSS Fix
```less
/**
 * Fix for PHP Language
 */
.syntax--use .syntax--class.syntax--php,
.syntax--method-call .syntax--entity.syntax--name.syntax--function,
.syntax--punctuation.syntax--definition.syntax--class.syntax--bracket.syntax--curly.syntax--php,
.syntax--punctuation.syntax--definition.syntax--class.syntax--bracket.syntax--curly.syntax--php,
.syntax--namespace + .syntax--class.syntax--php {
    color: #abb2bb;
}

.syntax--comment .syntax--class.syntax--php {
    color: #5c635f;
}
```

### Before
![before](https://user-images.githubusercontent.com/15145744/31632149-4ba93cfa-b292-11e7-908b-cfc8a29555c5.png)


### After
![after](https://user-images.githubusercontent.com/15145744/31632155-4f512b9c-b292-11e7-92f6-b337a4471600.png)
