### ISSUE TITLE
Change background color

### ISSUE THREAD

**Issue by andersennl** [atom/one-dark-syntax#19]
Hi, what css do I need to write into my custom css atom file if I want to decrease the brightness of the grey editor background?

It think it is a really good looking theme but for me personally the background is too bright to look at it all day long. (In the risk of the grey color being part of a color composition together with the other colors. Maybe there is a bigger thought behind this?) Thanks.

**Comment by simurai** [comment]
The current background color is: `hsl(222, 11%, 18%)`. To make it darker, you could change the last percentage (18%) to a lower number.. maybe something like this:

```less
// in your `styles.less` file
.theme-one-dark-ui atom-text-editor {
  background-color: hsl(222, 11%, 12%);
}
```
