### ISSUE TITLE
plaintext inside JSX not easily discerned from embedded JS

### ISSUE THREAD

**Issue by vith** [atom/one-dark-syntax#42]
I would like to see this mistake:
![screenshot from 2015-07-18 06 21 00](https://cloud.githubusercontent.com/assets/3265539/8761509/8ae51ee8-2d1a-11e5-8327-9df12b7bdd86.png)

be more visually dissimilar from the intended code:
![screenshot from 2015-07-18 06 22 13](https://cloud.githubusercontent.com/assets/3265539/8761515/a9393276-2d1a-11e5-94c0-e0440292d233.png)

like so:
![screenshot from 2015-07-18 06 21 24](https://cloud.githubusercontent.com/assets/3265539/8761514/a57fe698-2d1a-11e5-9bbc-7297c2df1939.png)

But I'm afraid [my implementation](https://github.com/atom/one-dark-syntax/compare/master...vith:jsx-textcontent-color) is too tightly coupled to [language-babel](https://github.com/gandm/language-babel). 

Would a PR for such an effect be wanted? If so, is `.meta.brace.curly.js` an appropriate thing to target to reset the style back to normal for JS blocks escaped by `{ }`?

**Comment by simurai** [comment]
> Would a PR for such an effect be wanted? If so, is .meta.brace.curly.js an appropriate thing to target to reset the style back to normal for JS blocks escaped by { }?

Good question. I checked out the [react](https://atom.io/packages/react) and [language-javascript-jsx](https://atom.io/packages/language-javascript-jsx) packages, but both use different highlighting. So yeah, your PR would be kinda too tied to the `language-babel` package.

I'm not too familiar with JSX, is omitting the braces invalid? If so, another option might be to make a PR for `language-babel` that changes the highlighting to hint that braces are required. Maybe add `.invalid.illegal` https://github.com/atom/one-dark-syntax/blob/master/styles/language.less#L250? Although that might be too strong and annoying.

Or if you just like to change it personally, you could add it to your `styles.less` (for now):

```less
// customize language-babel
.theme-one-dark-syntax atom-text-editor::shadow {
  .source.jsx {
    .markup.raw.jsx {
      color: #828997;
      .meta.brace.curly.js {
        color: #abb2bf;
      }
    }
  }
}
```

**Comment by vith** [comment]
It's not actually invalid without the braces, it's just treated as a plaintext string in the rendered HTML output instead of executed as javascript code. It doesn't mean what it looks like in my example without the braces, which is why I'd like the syntax highlighting to make that more obvious.

It looks like `language-javascript-jsx` has the best [labeling of the embedded section](https://github.com/subtleGradient/language-javascript-jsx/blob/4209756ea698a281f4176cac7f610af6847c54f0/grammars/JavaScript%20with%20JSX.cson#L23-L39) as it's consistent with how `language-php` labels [PHP sections in HTML](https://github.com/atom/language-php/blob/59385bb9186ede9c9bb7f788c5f80f2cc206d81a/grammars/php.cson#L33-L51), or `language-ruby` labeling [Ruby in HTML](https://github.com/atom/language-ruby/blob/32cf069f0363558b29918d1fc50039c2d70f38ef/grammars/html%20(ruby%20-%20erb).cson#L69-L94).

I updated my `one-dark-syntax` [fork](https://github.com/atom/one-dark-syntax/compare/master...vith:jsx-textcontent-color) to do this instead:
```less
// styles/languages/jsx.less
.source.jsx {
  .markup.raw.jsx {
    color: @mono-2;
  }
}
```
```less
// styles/language.less
.source {
  color: @mono-1;
}
```

And I've made a pull request to `language-babel` to fix the embedded section labeling here: https://github.com/gandm/language-babel/pull/29

**Comment by simurai** [comment]
Or just 

```less
// styles/languages/jsx.less
.source.jsx {
  color: @mono-1;

  .markup.raw.jsx {
    color: @mono-2;
  }
}
```

so it's scoped to JSX only? Although that still only affects `language-babel `.

Ok, this might be a stupid question, but isn't it a bit strange that `language-babel ` also includes JSX highlighting? Wouldn't it better if there is a separate `language-jsx ` package that becomes the "official" one? Currently there are a few packages that all do JSX highlighting but in a different way. Maybe it's still a bit early and one will emerge over time.

Hmm.. https://atom.io/packages/language-jsx seems to be taken by another language with the same name. :persevere:

Anyways, are you ok to keep it in your personal fork or `styles.less` for now? Although if you don't mind making a PR with the JSX spec only, that would be great to have.
