### ISSUE TITLE
Too Much Red Syntax Highlighting?

### ISSUE THREAD

**Issue by lukeschunk** [atom/one-dark-syntax#60]
I opened Atom today and noticed that my page had a LOT of red on it. I know this wasn't how it was before. For example, in the screenshot, `this.props.isLoading` should not be all red. I believe only the `this` was red before?

Any thoughts?
![screen shot 2016-01-14 at 2 09 05 pm](https://cloud.githubusercontent.com/assets/13579578/12337664/8bd13698-bac8-11e5-9faa-e087617de31e.png)
![screen shot 2016-01-14 at 2 10 31 pm](https://cloud.githubusercontent.com/assets/13579578/12337676/9952016c-bac8-11e5-9d4c-e5046833da82.png)

**Comment by 50Wliu** [comment]
Closing in favor of #54, atom/language-javascript#263, atom/language-javascript#258, atom/atom#9562

**Comment by lukeschunk** [comment]
Fair, but any idea why this would have happened suddenly? I didn't even update today.

**Comment by 50Wliu** [comment]
@lukeschunk Atom 1.4.0 was released yesterday, containing many language-javascript changes.  Your Atom probably automatically updated when you closed it.

**Comment by lukeschunk** [comment]
ahh thank you so much that must have been it @50Wliu

**Comment by RiCoTeRoX** [comment]
Hi @lukeschunk ,
I changed these classes to have the old styles, maybe it help you

atom-text-editor::shadow span.meta.method-call.js > span.variable.other.object.js {
  color: #abb2bf;
}
atom-text-editor::shadow span.meta.method-call.js > span.entity.name.function.js {
  color: #abb2bf;
}

atom-text-editor::shadow span.meta.method-call.js > span.variable.other.property.js {
  color: #abb2bf;
}

atom-text-editor::shadow span.source.js > span.variable.other.property.js {
  color: #abb2bf;
}

**Comment by marcelombc** [comment]
Revert to version to 0.100.0 or add this styles:

```css
atom-text-editor::shadow {
    .variable.other.object.js { color: #abb2bf; }
    .variable.other.property.js { color: #abb2bf; }
    span.meta.method-call.js {
        > span.entity.name.function.js { color: #abb2bf; }
    }
    span.meta.function-call.js {
        > span.entity.name.function.js { color: #abb2bf; }
    }
}
```

**Comment by MaximSokolov** [comment]
@RiCoTeRoX, @marcelombc to revert changes properly add this:
```less
@import "syntax-variables";

.theme-one-dark-syntax atom-text-editor::shadow .source.js {
  .variable.other.property, .variable.other.object {
    color: @syntax-text-color;
  }

  .meta.function-call, .meta.method-call {
    & > .entity.name.function {
      color: @syntax-text-color;
    }
  }
}
```
