### ISSUE TITLE
There is no visual separation between the gutter and the editing pane

### ISSUE THREAD

**Issue by eterevsky** [atom/one-dark-syntax#63]
Because the gutter is not visually separated from the editing pane, it is very hard to tell, where the first column is, and whether the cursor is currently at the start of the line, or not.

![screenshot from 2016-02-20 10-59-46](https://cloud.githubusercontent.com/assets/2182541/13195975/1694908a-d7c1-11e5-9a78-d3c4700121b9.png)

**Comment by mmcbride1007** [comment]
Personally I like the look, and I have to believe they intend for it to look that way. It's easy enough to just add something like the following to your own `stylesheet.less` for a visual cue:

```css
.gutter {
  border-right: 1px solid rgba(255,255,255,0.1);
}
```

Just my $0.02

**Comment by lee-dohm** [comment]
I'm pretty certain this is intentional also. If it is intentional and since a workaround is relatively simple, I'm inclined to mark this `wontfix`. I'll wait until @simurai lets us know his thoughts though.

**Comment by simurai** [comment]
Yes, this is intentional. Personally, I have the

- [x] Show Indent Guide

enabled in the settings. But if not, then yeah, it's kinda hard to tell if a line is indented or not.

In your `styles.less` file, you could:

## Border
Add a border (like @mmcbride1007 suggested):

```less
@import "syntax-variables";
atom-text-editor::shadow .gutter {
  border-right: 1px solid @syntax-indent-guide-color;
}
```

![screen shot 2016-02-23 at 1 09 16 pm](https://cloud.githubusercontent.com/assets/378023/13241492/e730bba0-da2e-11e5-9ddb-e2da3c3d0fda.png)


## Background

Add a background color. Maybe

```less
@import "syntax-variables";
atom-text-editor::shadow .gutter {
  background-color: lighten(@syntax-background-color, 5%);
}
```

![screen shot 2016-02-23 at 1 08 40 pm](https://cloud.githubusercontent.com/assets/378023/13241487/dba6a47a-da2e-11e5-84ec-e8a6b2d03d04.png)

**Comment by zwpaper** [comment]
@simurai I tried the solution, but I got two lines after the line number like the pic, could you help me please?
![image](https://cloud.githubusercontent.com/assets/3764335/16792423/ed9a44b2-48fa-11e6-8a19-30ea8037702a.png)

**Comment by simurai** [comment]
@zwpaper You probably have a package installed that adds a second gutter, like `linter`? Using the `.gutter-container` instead should only show one line:

```css
atom-text-editor::shadow .gutter-container {
  border-right: 1px solid rgba(255, 255, 255, 0.1);
}
```
