### ISSUE TITLE
`@supports not` triggers incorrectly colored CSS

### ISSUE THREAD

**Issue by maxvoltar** [atom/one-dark-syntax#64]
```css
@supports not (-webkit-backdrop-filter: blur(10px)) {
  background: rgba(230, 230, 230, 1);
}
```

All CSS that comes after the first line loses its color coding. 

Screenshot:
![screenshot 2016-03-08 14 25 24](https://cloud.githubusercontent.com/assets/125779/13618557/9cda551e-e539-11e5-8b01-4187758bb054.png)
