### ISSUE TITLE
Question about custom syntax

### ISSUE THREAD

**Issue by felixsanz** [atom/one-dark-syntax#91]
Inside syntax-variables.less you can see:

```less
// Custom Syntax Variables -----------------------------------
// Don't use in packages
```

What does that mean? The variables **ARE** used inside, so why don't use them in our own themes if the variable is used? For example:

```less
/* editor.less */
  .line.cursor-line {
    background-color: @syntax-cursor-line;
  }
```
